config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root to: 'home_search#start'
  get '/search', to: 'home_search#search'
  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/home_search_controller.rb
# frozen_string_literal: true

class HomeSearchController < ApplicationController # :nodoc:
  before_action :define_list

  def start; end

  def search
    @updated_list = List.new.search_with_query(params[:query])

    render turbo_stream:
    update_list
  end

  private

  def define_list
    # Initialize JSON data list and query from user
    @list = JSON.parse(File.read('storage/data.json'))
  end

  # Update list using wireless turbo
  def update_list
    turbo_stream.update 'list', partial: 'list', locals: { list: @updated_list }
  end
end

app/views/home_search/_list.html.erb
<% if list.present? %>
  <% list.each do |one| %>
    <div class = ' text-left px-2 py-1 space-x-4 border-2'>
      <div>
        Name: "<%= one["Name"] %>"
      </div>

      <div>
        Types:

        <%= render "sub_element_list", elements: one["Type"].split(', ') %>
      </div>

      <div>
        Authors:
            <%= render "sub_element_list", elements: one["Designed by"].split(', ') %>
      </div>

    </div>
  <% end %>
<% else %>
  <div>
    Nothing wasn't found :(
  </div>
<% end %>

app/views/home_search/_sub_element_list.html.erb
<% elements.each do |element|%>
  <li class = 'mx-8'>
    <%= element%>
  </li>
<% end %>

app/views/home_search/start.html.erb
<div class = 'container flex flex-col items-center justify-center '>
  <div id = 'search_container'>
  <%= form_with url: search_path(list: @list), method: :get, class: "flex flex-col items-center" do |form| %>
    <%= form.label "Search" %>
    <%= form.text_field :query %>
    <%= form.submit "Find", class: "bg-green-200 w-32 h-8 my-4" %>
  <% end %>
  </div>

  <div id = 'list'>
    <%= render "list", list: @list%>
  </div>

</div>